"""requester_id nullable for staff-created tickets

PLAN.md Phase 14: a ticket can now be "unclaimed" - staff-created for a
customer with no account yet, tagged only with an organisation, and linked
to a real end_user once one exists. Downgrade's NOT NULL would fail if any
unclaimed ticket exists by then; that's expected (data-losing downgrades
aren't meant to run against real data).

As with the last two migrations, autogenerate also proposed dropping the
two raw-SQL functional indexes (ix_knowledge_base_articles_search,
ix_organizations_name_lower) - the same false positive from comparing
against indexes with no ORM-side `Index()` declaration, removed here too.

Revision ID: 21bb89cebd7d
Revises: 2e14096d9fa6
Create Date: 2026-09-29 13:44:02.398522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bb89cebd7d'
down_revision: Union[str, None] = '2e14096d9fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'requester_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
