"""login attempts for password-step throttling

PLAN.md Phase 13: rate-limits POST /auth/login per email and per client IP.
One row per failed attempt, keyed so the counters work across several Cloud
Run instances (in-memory counting wouldn't).

As with e7fd6f01d856, autogenerate also proposed dropping the two raw-SQL
functional indexes (ix_knowledge_base_articles_search,
ix_organizations_name_lower) - the same false positive from comparing
against indexes with no ORM-side `Index()` declaration, removed here too.

Revision ID: 2e14096d9fa6
Revises: e7fd6f01d856
Create Date: 2026-09-29 11:06:35.312227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e14096d9fa6'
down_revision: Union[str, None] = 'e7fd6f01d856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip'), 'login_attempts', ['ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_attempts_ip'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
