"""kb embedding model and query indexes

Phase 3 follow-ups from PLAN.md (do first):
- knowledge_base_articles.embedding_model: tracks which model produced the
  stored vector, so seed.py can re-embed articles when the provider changes
  (fake vs Gemini) instead of comparing stale and current vectors.
- audit_log(entity_type, entity_id) composite index: the audit trail is
  always looked up by entity.
- tickets.status / tickets.priority indexes: both are filter columns on
  GET /tickets.

Revision ID: 479c142aad4c
Revises: d1faf9909ccb
Create Date: 2026-09-24 10:46:25.977069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479c142aad4c'
down_revision: Union[str, None] = 'd1faf9909ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_log_entity_type_entity_id', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.add_column('knowledge_base_articles', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tickets_priority'), 'tickets', ['priority'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_priority'), table_name='tickets')
    op.drop_column('knowledge_base_articles', 'embedding_model')
    op.drop_index('ix_audit_log_entity_type_entity_id', table_name='audit_log')
    # ### end Alembic commands ###
