"""organizations and ticket action items

PLAN.md Phase 12: which organisation (company or government entity) has the
problem, and two per-ticket action-item checklists (customer / LiverX).

- organizations: id, name (case-insensitive unique via a functional index on
  lower(name), since a plain UNIQUE constraint would let "Acme" and "ACME"
  collide as different rows), kind, active.
- users.organization_id, tickets.organization_id: nullable FKs.
- ticket_action_items: side, description, done + who/when it was done.

Autogenerate also proposed dropping ix_knowledge_base_articles_search (a
raw-SQL GIN index with no SQLAlchemy-side declaration, so it isn't in the
declarative metadata autogenerate diffs against) - that's a false positive
from comparing against an undeclared index, not an intended change, and is
removed from this migration.

Known limitation, expected going forward: `alembic check` will always list
ix_knowledge_base_articles_search and the new ix_organizations_name_lower as
"removed", for the same reason (both are raw-SQL functional/expression
indexes with no ORM-side `Index()` declaration). Verify these two by name
directly (psql's describe-table command, or a pg_indexes query), not by an
empty `alembic check`.

Revision ID: e7fd6f01d856
Revises: 6c554119e30e
Create Date: 2026-09-29 09:52:25.069263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fd6f01d856'
down_revision: Union[str, None] = '6c554119e30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('company', 'government', name='organization_kind'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('customer', 'liverx', name='action_item_side'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_action_items_ticket_id'), 'ticket_action_items', ['ticket_id'], unique=False)
    op.execute(
        "CREATE UNIQUE INDEX ix_organizations_name_lower ON organizations (lower(name))"
    )
    op.add_column('tickets', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tickets_organization_id'), 'tickets', ['organization_id'], unique=False)
    op.create_foreign_key(
        'fk_tickets_organization_id_organizations', 'tickets', 'organizations', ['organization_id'], ['id']
    )
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_foreign_key(
        'fk_users_organization_id_organizations', 'users', 'organizations', ['organization_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_organization_id_organizations', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_constraint('fk_tickets_organization_id_organizations', 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_organization_id'), table_name='tickets')
    op.drop_column('tickets', 'organization_id')
    op.drop_index(op.f('ix_ticket_action_items_ticket_id'), table_name='ticket_action_items')
    op.drop_table('ticket_action_items')
    op.execute("DROP INDEX IF EXISTS ix_organizations_name_lower")
    op.drop_table('organizations')
    for enum in ('action_item_side', 'organization_kind'):
        op.execute(f'DROP TYPE IF EXISTS {enum}')
    # ### end Alembic commands ###
